version: '3.1'

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: es
      POSTGRES_PASSWORD: es
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3.11.2-management
    ports:
      - '5672:5672'
      - '15672:15672'

  kurrentdb:
    image: kurrentplatform/kurrentdb
    environment:
      - KURRENTDB_CLUSTER_SIZE=1
      - KURRENTDB_RUN_PROJECTIONS=All
      - KURRENTDB_START_STANDARD_PROJECTIONS=true
      - KURRENTDB_INSECURE=true
      - KURRENTDB_ENABLE_ATOM_PUB_OVER_HTTP=true
      - KURRENTDB_NODE_PORT=2113
    ports:
      - "2113:2113"
      
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 5s
      timeout: 3s
      retries: 5
