site_name: Event Sourcery
theme:
  name: material
  palette:
    primary: deep purple
repo_url: https://github.com/python-event-sourcery/python-event-sourcery/
repo_name: python-event-sourcery/python-event-sourcery
nav:
    - 'Event Sourcery': 'index.md'
    - '<b>Concepts</b>':
        - 'Basics': 'concepts/basics.md'
    - '<b>Recipes</b>':
        - 'ğŸï¸ Defining events': 'recipes/defining_events.md'
        - 'ğŸ”— Integrate with your app': 'recipes/integrate.md'
        - 'ğŸ“ Save and read events': 'recipes/saving_events.md'
        - 'ğŸ—ï¸ React to events - subscriptions': 'recipes/subscriptions.md'
        - 'ğŸ“¤ Publish events - outbox': 'recipes/outbox.md'
        - 'ğŸ›ï¸ Event Sourcing': 'recipes/event_sourcing.md'
        - 'ğŸ‘«ï¸ Multitenancy': 'recipes/multitenancy.md'
        - 'ğŸ“· Snapshots': 'recipes/snapshots.md'
    - '<b>API Reference</b>':
        - 'Event Store': 'reference/event_store.md'
        - 'StreamId': 'reference/stream_id.md'
        - 'Event': 'reference/event.md'
        - 'WrappedEvent': 'reference/wrapped_event.md'
        - 'Recorded': 'reference/recorded.md'
        - 'BackendFactory': 'reference/backend_factory.md'
        - 'EventRegistry': 'reference/event_registry.md'
        - 'InMemoryBackendFactory': 'reference/in_memory_backend_factory.md'

plugins:
- search
- mkdocstrings

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.snippets:
      check_paths: true
      dedent_subsections: true
  - pymdownx.superfences
  - tables
